# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.btnGeneratePlaces = QtWidgets.QPushButton(self.centralwidget)
        self.btnGeneratePlaces.setGeometry(QtCore.QRect(10, 20, 231, 31))
        self.btnGeneratePlaces.setObjectName("btnGeneratePlaces")
        self.btnGenerateWeights = QtWidgets.QPushButton(self.centralwidget)
        self.btnGenerateWeights.setGeometry(QtCore.QRect(10, 60, 231, 31))
        self.btnGenerateWeights.setObjectName("btnGenerateWeights")
        self.btnGenerateResults = QtWidgets.QPushButton(self.centralwidget)
        self.btnGenerateResults.setGeometry(QtCore.QRect(10, 100, 231, 31))
        self.btnGenerateResults.setObjectName("btnGenerateResults")
        self.btnChooseCurrentPath = QtWidgets.QPushButton(self.centralwidget)
        self.btnChooseCurrentPath.setGeometry(QtCore.QRect(10, 490, 201, 31))
        self.btnChooseCurrentPath.setObjectName("btnChooseCurrentPath")
        self.textCurrentPath = QtWidgets.QLabel(self.centralwidget)
        self.textCurrentPath.setGeometry(QtCore.QRect(10, 530, 81, 16))
        self.textCurrentPath.setObjectName("textCurrentPath")
        self.textChosenCurrentPath = QtWidgets.QLabel(self.centralwidget)
        self.textChosenCurrentPath.setGeometry(QtCore.QRect(90, 530, 571, 16))
        self.textChosenCurrentPath.setObjectName("textChosenCurrentPath")
        self.listParticipants = QtWidgets.QListWidget(self.centralwidget)
        self.listParticipants.setGeometry(QtCore.QRect(360, 30, 421, 361))
        self.listParticipants.setObjectName("listParticipants")
        self.textParticipants = QtWidgets.QLabel(self.centralwidget)
        self.textParticipants.setGeometry(QtCore.QRect(360, 10, 61, 16))
        self.textParticipants.setObjectName("textParticipants")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        self.menuProgram = QtWidgets.QMenu(self.menubar)
        self.menuProgram.setObjectName("menuProgram")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menuProgramActionQuit = QtWidgets.QAction(MainWindow)
        self.menuProgramActionQuit.setObjectName("menuProgramActionQuit")
        self.menuHelpActionOpenHelp = QtWidgets.QAction(MainWindow)
        self.menuHelpActionOpenHelp.setObjectName("menuHelpActionOpenHelp")
        self.menuProgram.addAction(self.menuProgramActionQuit)
        self.menuHelp.addAction(self.menuHelpActionOpenHelp)
        self.menubar.addAction(self.menuProgram.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btnGeneratePlaces.setText(_translate("MainWindow", "Сгенерировать стартовые позиции"))
        self.btnGenerateWeights.setText(_translate("MainWindow", "Сгенерировать довесы"))
        self.btnGenerateResults.setText(_translate("MainWindow", "Сгенерировать итоговые результаты"))
        self.btnChooseCurrentPath.setText(_translate("MainWindow", "Указать путь к файлу с участниками"))
        self.textCurrentPath.setText(_translate("MainWindow", "Текущий путь:"))
        self.textChosenCurrentPath.setText(_translate("MainWindow", "Выберите файл с участниками"))
        self.textParticipants.setText(_translate("MainWindow", "Участники"))
        self.menuProgram.setTitle(_translate("MainWindow", "Программа"))
        self.menuHelp.setTitle(_translate("MainWindow", "Справка"))
        self.menuProgramActionQuit.setText(_translate("MainWindow", "Выйти"))
        self.menuHelpActionOpenHelp.setText(_translate("MainWindow", "Открыть справку"))
