# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'toolGenerateWeightsWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_toolGenerateWeightsWindow(object):
    def setupUi(self, toolGenerateWeightsWindow):
        toolGenerateWeightsWindow.setObjectName("toolGenerateWeightsWindow")
        toolGenerateWeightsWindow.resize(400, 200)
        self.centralwidget = QtWidgets.QWidget(toolGenerateWeightsWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.textGenerateMethod = QtWidgets.QLabel(self.centralwidget)
        self.textGenerateMethod.setGeometry(QtCore.QRect(10, 10, 101, 21))
        self.textGenerateMethod.setObjectName("textGenerateMethod")
        self.boxGenerateMethod = QtWidgets.QComboBox(self.centralwidget)
        self.boxGenerateMethod.setGeometry(QtCore.QRect(200, 10, 191, 22))
        self.boxGenerateMethod.setObjectName("boxGenerateMethod")
        self.boxGenerateMethod.addItem("")
        self.boxGenerateMethod.addItem("")
        self.textWeightTick = QtWidgets.QLabel(self.centralwidget)
        self.textWeightTick.setGeometry(QtCore.QRect(10, 40, 101, 21))
        self.textWeightTick.setObjectName("textWeightTick")
        self.boxWeightTick = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.boxWeightTick.setGeometry(QtCore.QRect(200, 40, 62, 22))
        self.boxWeightTick.setObjectName("boxWeightTick")
        self.boxWeightGoal = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.boxWeightGoal.setGeometry(QtCore.QRect(200, 100, 62, 22))
        self.boxWeightGoal.setMaximum(149.99)
        self.boxWeightGoal.setProperty("value", 50.0)
        self.boxWeightGoal.setObjectName("boxWeightGoal")
        self.textWeightGoal1 = QtWidgets.QLabel(self.centralwidget)
        self.textWeightGoal1.setGeometry(QtCore.QRect(10, 95, 171, 16))
        self.textWeightGoal1.setObjectName("textWeightGoal1")
        self.textWeightGoal2 = QtWidgets.QLabel(self.centralwidget)
        self.textWeightGoal2.setGeometry(QtCore.QRect(7, 106, 191, 16))
        self.textWeightGoal2.setObjectName("textWeightGoal2")
        self.boxMaxKartWeight = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.boxMaxKartWeight.setGeometry(QtCore.QRect(200, 70, 62, 22))
        self.boxMaxKartWeight.setObjectName("boxMaxKartWeight")
        self.textMaxKartWeight = QtWidgets.QLabel(self.centralwidget)
        self.textMaxKartWeight.setGeometry(QtCore.QRect(10, 70, 151, 21))
        self.textMaxKartWeight.setObjectName("textMaxKartWeight")
        self.btnGenerate = QtWidgets.QPushButton(self.centralwidget)
        self.btnGenerate.setGeometry(QtCore.QRect(280, 130, 111, 41))
        self.btnGenerate.setObjectName("btnGenerate")
        toolGenerateWeightsWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(toolGenerateWeightsWindow)
        self.statusbar.setObjectName("statusbar")
        toolGenerateWeightsWindow.setStatusBar(self.statusbar)

        self.retranslateUi(toolGenerateWeightsWindow)
        QtCore.QMetaObject.connectSlotsByName(toolGenerateWeightsWindow)

    def retranslateUi(self, toolGenerateWeightsWindow):
        _translate = QtCore.QCoreApplication.translate
        toolGenerateWeightsWindow.setWindowTitle(_translate("toolGenerateWeightsWindow", "MainWindow"))
        self.textGenerateMethod.setText(_translate("toolGenerateWeightsWindow", "Способ генерации"))
        self.boxGenerateMethod.setCurrentText(_translate("toolGenerateWeightsWindow", "До максимального веса"))
        self.boxGenerateMethod.setItemText(0, _translate("toolGenerateWeightsWindow", "До максимального веса"))
        self.boxGenerateMethod.setItemText(1, _translate("toolGenerateWeightsWindow", "До указанного веса"))
        self.textWeightTick.setText(_translate("toolGenerateWeightsWindow", "Шаг довеса"))
        self.textWeightGoal1.setText(_translate("toolGenerateWeightsWindow", "Цель довеса (не указывается"))
        self.textWeightGoal2.setText(_translate("toolGenerateWeightsWindow", " при довесе до максимального веса)"))
        self.textMaxKartWeight.setText(_translate("toolGenerateWeightsWindow", "Максимальный довес на карт"))
        self.btnGenerate.setText(_translate("toolGenerateWeightsWindow", "Сгенерировать"))
